[package]
name = "steamworks-sys"
version = "0.6.1"
authors = ["Thinkofname"]
build = "build.rs"
description = "Provides raw bindings to the steamworks sdk"
license = "MIT / Apache-2.0"
repository = "https://github.com/Thinkofname/steamworks-rs"
documentation = "https://docs.rs/steamworks-sys"

[package.metadata.docs.rs]
features = [ "docs-only" ]


[features]
default = []
# Skip looking for the steamworks sdk for docs builds
docs-only = []


[dependencies]
libc = "0.2.50"

[build-dependencies]
bindgen = "0.53.1"
